apiVersion: v1
kind: Service
metadata:
  name: fullstack-service
spec:
  type: NodePort
  selector:
    app: fullstack
  ports:
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 30080
